### ISSUE TITLE
Building the image

### ISSUE THREAD

**Issue by KillahB33** [e1z0/jetson-frigate#2]
I have similar issues as the other guys so I am in the process of pulling the image you have uploaded.
So I got yours running which is fantastic! (huge thank you there) but wanted to contribute back to the original project so it's available for others, so trying to figure out how we can do that cause based on what I saw it was only ffmpeg that changed but please correct me if I am wrong.

Want to make this config stuff public though cause that's the most frustrating thing right now.

docker-compose.yaml

```
version: "3.8"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: nulldevil/frigate
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: '1000mb'
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/config/frigate/config.yml:/config/config.yml:ro
      - /opt/config/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD="********"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
```
      
config.yaml (just doing this part cause everything else is standard)

```
detectors:
  coral:
    type: edgetpu
    device: pci
ffmpeg:
  hwaccel_args:
    - -c:v h264_nvmpi
```
